CREATE TABLE "rudal_combat" (
  "nama" char(50),
  "jenis" char(50),
  "deskripsi" char(100),
  "satuan" char(50),
  "kode_asset" char(50),
  "pabrikan" char(50),
  "negara" char(10),
  "tahun_produksi" int4,
  "penyedia" char(50),
  "tahun_perolehan" int4,
  "kondisi" char(50),
  "harga" int4,
  "umur_ekonomis" int4,
  "no_seri_pabrik" char(20),
  "berat" float4,
  "dimensi" float4,
  "diameter" float4,
  "jenis_amunisi" char(50),
  "kecepatan_luncur" float4,
  "penetrasi" float4
);

CREATE TABLE "rudal_training_per_captive" (
  "nama" char(50),
  "jenis" char(50),
  "deskripsi" char(100),
  "satuan" char(50),
  "kode_asset" char(50),
  "pabrikan" char(50),
  "negara" char(10),
  "tahun_produksi" int4,
  "penyedia" char(50),
  "tahun_perolehan" int4,
  "kondisi" char(50),
  "harga" int4,
  "umur_ekonomis" int4,
  "no_seri_pabrik" char(20),
  "berat" float4,
  "dimensi" float4,
  "diameter" float4,
  "jenis_amunisi" char(50),
  "kecepatan_luncur" float4,
  "penetrasi" float4
);

