CREATE TABLE "crypto_device" (
  "jenis" char(50),
  "nama" char(50),
  "deskripsi" char(100),
  "satuan" char(50),
  "penyedia" char(50),
  "tahun_perolehan" int4,
  "kode_asset" char(20),
  "negara_asal" char(10),
  "pabrikan" char(50),
  "kondisi" char(50),
  "harga" int4,
  "umur_ekonomis" int4,
  "tahun_produksi" int4,
  "no_seri_pabrik" char,
  "berat" float4,
  "frekuensi_perlindungan" float4,
  "pengidentifikasi_ancaman" float4,
  "waktu_respon" float4,
  "jenis_ancaman" float4,
  "keamanan_sistem" int4,
  "deteksi_dini" char(5),
  "reduksi_peluang_deteksi" char(100)
);

CREATE TABLE "radio_hopping" (
  "jenis" char(50),
  "nama" char(50),
  "deskripsi" char(100),
  "satuan" char(50),
  "penyedia" char(50),
  "tahun_perolehan" int4,
  "kode_asset" char(20),
  "negara_asal" char(10),
  "pabrikan" char(50),
  "kondisi" char(50),
  "harga" int4,
  "umur_ekonomis" int4,
  "tahun_produksi" int4,
  "no_seri_pabrik" char,
  "berat" float4,
  "frekuensi_perlindungan" float4,
  "pengidentifikasi_ancaman" float4,
  "waktu_respon" float4,
  "jenis_ancaman" float4,
  "keamanan_sistem" int4,
  "deteksi_dini" char(5),
  "reduksi_peluang_deteksi" char(100)
);

