CREATE TABLE "darat" (
  "jenis" char(50),
  "nama" char(50),
  "deskripsi" char(100),
  "satuan" char(50),
  "penyedia" char(50),
  "tahun_perolehan" int4,
  "kode_asset" char(20),
  "negara_asal" char(10),
  "pabrikan" char(50),
  "kondisi" char(50),
  "harga" int4,
  "umur_ekonomis" int4,
  "tahun_produksi" int4,
  "no_seri_pabrik" char(20),
  "berat" float4,
  "frekuensi_operasi" float4,
  "daya_keluar" float4,
  "kemampuan_penargetan" float4,
  "jangkauan_efektif" float4,
  "modulasi" int2,
  "jenis_sinyal" char(5)
);

CREATE TABLE "laut" (
  "jenis" char(50),
  "nama" char(50),
  "deskripsi" char(100),
  "satuan" char(50),
  "penyedia" char(50),
  "tahun_perolehan" int4,
  "kode_asset" char(20),
  "negara_asal" char(10),
  "pabrikan" char(50),
  "kondisi" char(50),
  "harga" int4,
  "umur_ekonomis" int4,
  "tahun_produksi" int4,
  "no_seri_pabrik" char(20),
  "berat" float4,
  "frekuensi_operasi" float4,
  "daya_keluar" float4,
  "kemampuan_penargetan" float4,
  "jangkauan_efektif" float4,
  "modulasi" int2,
  "jenis_sinyal" char(5)
);

CREATE TABLE "udara" (
  "jenis" char(50),
  "nama" char(50),
  "deskripsi" char(100),
  "satuan" char(50),
  "penyedia" char(50),
  "tahun_perolehan" int4,
  "kode_asset" char(20),
  "negara_asal" char(10),
  "pabrikan" char(50),
  "kondisi" char(50),
  "harga" int4,
  "umur_ekonomis" int4,
  "tahun_produksi" int4,
  "no_seri_pabrik" char(20),
  "berat" float4,
  "frekuensi_operasi" float4,
  "daya_keluar" float4,
  "kemampuan_penargetan" float4,
  "jangkauan_efektif" float4,
  "modulasi" int2,
  "jenis_sinyal" char(5)
);

