CREATE TABLE "electronic_support" (
  "jenis" char(50),
  "nama" char(50),
  "deskripsi" char(100),
  "satuan" char(50),
  "penyedia" char(50),
  "tahun_perolehan" int4,
  "kode_asset" char(20),
  "negara_asal" char(20),
  "pabrikan" char(50),
  "kondisi" char(50),
  "harga" int4,
  "umur_ekonomis" int4,
  "tahun_produksi" int4,
  "no_seri_pabrik" char(20),
  "berat" float4,
  "panjang_badan" float4,
  "panjang_badan_dengan_senjata" float4,
  "lebar" float4,
  "tinggi" float4,
  "awak" int2,
  "perisai" char(5),
  "senjata_utama" char(100),
  "senjata_pelengkap" char(100),
  "jenis_mesin" char(100),
  "tenaga" float4,
  "transmisi" char(50),
  "suspensi" char(50),
  "ground_clearence" float4,
  "jarak_tempuh_di_jalan_umum" float4,
  "jarak_tempuh_di_medan_perang" float4,
  "kecepatan_maksimal_di_jalan_umum" float4,
  "kecepatan_maksimal_di_medan_perang" float4
);

