CREATE TABLE "Tnt_10_kg" (
  "nama" char(50),
  "jenis" char(50),
  "deskripsi" char(100),
  "satuan" char(50),
  "kode_asset" char(50),
  "pabrikan" char(50),
  "negara" char(10),
  "tahun_produksi" int4,
  "penyedia" char(50),
  "tahun_perolehan" int4,
  "kondisi" char(50),
  "harga" int4,
  "umur_ekonomis" int4,
  "no_seri_pabrik" char(20),
  "berat" float4,
  "dimensi" float4,
  "diameter" float4,
  "jenis_amunisi" char(50),
  "kecepatan_luncur" float4,
  "penetrasi" float4
);

CREATE TABLE "Tnt_30_gram" (
  "nama" char(50),
  "jenis" char(50),
  "deskripsi" char(100),
  "satuan" char(50),
  "kode_asset" char(50),
  "pabrikan" char(50),
  "negara" char(10),
  "tahun_produksi" int4,
  "penyedia" char(50),
  "tahun_perolehan" int4,
  "kondisi" char(50),
  "harga" int4,
  "umur_ekonomis" int4,
  "no_seri_pabrik" char(20),
  "berat" float4,
  "dimensi" float4,
  "diameter" float4,
  "jenis_amunisi" char(50),
  "kecepatan_luncur" float4,
  "penetrasi" float4
);

CREATE TABLE "Tnt_60_gram" (
  "nama" char(50),
  "jenis" char(50),
  "deskripsi" char(100),
  "satuan" char(50),
  "kode_asset" char(50),
  "pabrikan" char(50),
  "negara" char(10),
  "tahun_produksi" int4,
  "penyedia" char(50),
  "tahun_perolehan" int4,
  "kondisi" char(50),
  "harga" int4,
  "umur_ekonomis" int4,
  "no_seri_pabrik" char(20),
  "berat" float4,
  "dimensi" float4,
  "diameter" float4,
  "jenis_amunisi" char(50),
  "kecepatan_luncur" float4,
  "penetrasi" float4
);

CREATE TABLE "Tnt_60_gram_slooping" (
  "nama" char(50),
  "jenis" char(50),
  "deskripsi" char(100),
  "satuan" char(50),
  "kode_asset" char(50),
  "pabrikan" char(50),
  "negara" char(10),
  "tahun_produksi" int4,
  "penyedia" char(50),
  "tahun_perolehan" int4,
  "kondisi" char(50),
  "harga" int4,
  "umur_ekonomis" int4,
  "no_seri_pabrik" char(20),
  "berat" float4,
  "dimensi" float4,
  "diameter" float4,
  "jenis_amunisi" char(50),
  "kecepatan_luncur" float4,
  "penetrasi" float4
);

CREATE TABLE "Tnt_75_gram" (
  "nama" char(50),
  "jenis" char(50),
  "deskripsi" char(100),
  "satuan" char(50),
  "kode_asset" char(50),
  "pabrikan" char(50),
  "negara" char(10),
  "tahun_produksi" int4,
  "penyedia" char(50),
  "tahun_perolehan" int4,
  "kondisi" char(50),
  "harga" int4,
  "umur_ekonomis" int4,
  "no_seri_pabrik" char(20),
  "berat" float4,
  "dimensi" float4,
  "diameter" float4,
  "jenis_amunisi" char(50),
  "kecepatan_luncur" float4,
  "penetrasi" float4
);

CREATE TABLE "Tnt_100_gram" (
  "nama" char(50),
  "jenis" char(50),
  "deskripsi" char(100),
  "satuan" char(50),
  "kode_asset" char(50),
  "pabrikan" char(50),
  "negara" char(10),
  "tahun_produksi" int4,
  "penyedia" char(50),
  "tahun_perolehan" int4,
  "kondisi" char(50),
  "harga" int4,
  "umur_ekonomis" int4,
  "no_seri_pabrik" char(20),
  "berat" float4,
  "dimensi" float4,
  "diameter" float4,
  "jenis_amunisi" char(50),
  "kecepatan_luncur" float4,
  "penetrasi" float4
);

CREATE TABLE "Tnt_112_5_gram_1_per_4_lb" (
  "nama" char(50),
  "jenis" char(50),
  "deskripsi" char(100),
  "satuan" char(50),
  "kode_asset" char(50),
  "pabrikan" char(50),
  "negara" char(10),
  "tahun_produksi" int4,
  "penyedia" char(50),
  "tahun_perolehan" int4,
  "kondisi" char(50),
  "harga" int4,
  "umur_ekonomis" int4,
  "no_seri_pabrik" char(20),
  "berat" float4,
  "dimensi" float4,
  "diameter" float4,
  "jenis_amunisi" char(50),
  "kecepatan_luncur" float4,
  "penetrasi" float4
);

CREATE TABLE "Tnt_130_gram" (
  "nama" char(50),
  "jenis" char(50),
  "deskripsi" char(100),
  "satuan" char(50),
  "kode_asset" char(50),
  "pabrikan" char(50),
  "negara" char(10),
  "tahun_produksi" int4,
  "penyedia" char(50),
  "tahun_perolehan" int4,
  "kondisi" char(50),
  "harga" int4,
  "umur_ekonomis" int4,
  "no_seri_pabrik" char(20),
  "berat" float4,
  "dimensi" float4,
  "diameter" float4,
  "jenis_amunisi" char(50),
  "kecepatan_luncur" float4,
  "penetrasi" float4
);

CREATE TABLE "Tnt_130_gram_slooping" (
  "nama" char(50),
  "jenis" char(50),
  "deskripsi" char(100),
  "satuan" char(50),
  "kode_asset" char(50),
  "pabrikan" char(50),
  "negara" char(10),
  "tahun_produksi" int4,
  "penyedia" char(50),
  "tahun_perolehan" int4,
  "kondisi" char(50),
  "harga" int4,
  "umur_ekonomis" int4,
  "no_seri_pabrik" char(20),
  "berat" float4,
  "dimensi" float4,
  "diameter" float4,
  "jenis_amunisi" char(50),
  "kecepatan_luncur" float4,
  "penetrasi" float4
);

CREATE TABLE "Tnt_160_gram" (
  "nama" char(50),
  "jenis" char(50),
  "deskripsi" char(100),
  "satuan" char(50),
  "kode_asset" char(50),
  "pabrikan" char(50),
  "negara" char(10),
  "tahun_produksi" int4,
  "penyedia" char(50),
  "tahun_perolehan" int4,
  "kondisi" char(50),
  "harga" int4,
  "umur_ekonomis" int4,
  "no_seri_pabrik" char(20),
  "berat" float4,
  "dimensi" float4,
  "diameter" float4,
  "jenis_amunisi" char(50),
  "kecepatan_luncur" float4,
  "penetrasi" float4
);

CREATE TABLE "Tnt_200_400_gram" (
  "nama" char(50),
  "jenis" char(50),
  "deskripsi" char(100),
  "satuan" char(50),
  "kode_asset" char(50),
  "pabrikan" char(50),
  "negara" char(10),
  "tahun_produksi" int4,
  "penyedia" char(50),
  "tahun_perolehan" int4,
  "kondisi" char(50),
  "harga" int4,
  "umur_ekonomis" int4,
  "no_seri_pabrik" char(20),
  "berat" float4,
  "dimensi" float4,
  "diameter" float4,
  "jenis_amunisi" char(50),
  "kecepatan_luncur" float4,
  "penetrasi" float4
);

CREATE TABLE "Tnt_200_gram" (
  "nama" char(50),
  "jenis" char(50),
  "deskripsi" char(100),
  "satuan" char(50),
  "kode_asset" char(50),
  "pabrikan" char(50),
  "negara" char(10),
  "tahun_produksi" int4,
  "penyedia" char(50),
  "tahun_perolehan" int4,
  "kondisi" char(50),
  "harga" int4,
  "umur_ekonomis" int4,
  "no_seri_pabrik" char(20),
  "berat" float4,
  "dimensi" float4,
  "diameter" float4,
  "jenis_amunisi" char(50),
  "kecepatan_luncur" float4,
  "penetrasi" float4
);

CREATE TABLE "Tnt_225_gram_1_per_2_lb" (
  "nama" char(50),
  "jenis" char(50),
  "deskripsi" char(100),
  "satuan" char(50),
  "kode_asset" char(50),
  "pabrikan" char(50),
  "negara" char(10),
  "tahun_produksi" int4,
  "penyedia" char(50),
  "tahun_perolehan" int4,
  "kondisi" char(50),
  "harga" int4,
  "umur_ekonomis" int4,
  "no_seri_pabrik" char(20),
  "berat" float4,
  "dimensi" float4,
  "diameter" float4,
  "jenis_amunisi" char(50),
  "kecepatan_luncur" float4,
  "penetrasi" float4
);

CREATE TABLE "Tnt_225_gram_slooping" (
  "nama" char(50),
  "jenis" char(50),
  "deskripsi" char(100),
  "satuan" char(50),
  "kode_asset" char(50),
  "pabrikan" char(50),
  "negara" char(10),
  "tahun_produksi" int4,
  "penyedia" char(50),
  "tahun_perolehan" int4,
  "kondisi" char(50),
  "harga" int4,
  "umur_ekonomis" int4,
  "no_seri_pabrik" char(20),
  "berat" float4,
  "dimensi" float4,
  "diameter" float4,
  "jenis_amunisi" char(50),
  "kecepatan_luncur" float4,
  "penetrasi" float4
);

CREATE TABLE "Tnt_400_gram" (
  "nama" char(50),
  "jenis" char(50),
  "deskripsi" char(100),
  "satuan" char(50),
  "kode_asset" char(50),
  "pabrikan" char(50),
  "negara" char(10),
  "tahun_produksi" int4,
  "penyedia" char(50),
  "tahun_perolehan" int4,
  "kondisi" char(50),
  "harga" int4,
  "umur_ekonomis" int4,
  "no_seri_pabrik" char(20),
  "berat" float4,
  "dimensi" float4,
  "diameter" float4,
  "jenis_amunisi" char(50),
  "kecepatan_luncur" float4,
  "penetrasi" float4
);

CREATE TABLE "Tnt_450_1_lb" (
  "nama" char(50),
  "jenis" char(50),
  "deskripsi" char(100),
  "satuan" char(50),
  "kode_asset" char(50),
  "pabrikan" char(50),
  "negara" char(10),
  "tahun_produksi" int4,
  "penyedia" char(50),
  "tahun_perolehan" int4,
  "kondisi" char(50),
  "harga" int4,
  "umur_ekonomis" int4,
  "no_seri_pabrik" char(20),
  "berat" float4,
  "dimensi" float4,
  "diameter" float4,
  "jenis_amunisi" char(50),
  "kecepatan_luncur" float4,
  "penetrasi" float4
);

CREATE TABLE "Tnt_500_gram" (
  "nama" char(50),
  "jenis" char(50),
  "deskripsi" char(100),
  "satuan" char(50),
  "kode_asset" char(50),
  "pabrikan" char(50),
  "negara" char(10),
  "tahun_produksi" int4,
  "penyedia" char(50),
  "tahun_perolehan" int4,
  "kondisi" char(50),
  "harga" int4,
  "umur_ekonomis" int4,
  "no_seri_pabrik" char(20),
  "berat" float4,
  "dimensi" float4,
  "diameter" float4,
  "jenis_amunisi" char(50),
  "kecepatan_luncur" float4,
  "penetrasi" float4
);

CREATE TABLE "Tnt_550_per_575_gram" (
  "nama" char(50),
  "jenis" char(50),
  "deskripsi" char(100),
  "satuan" char(50),
  "kode_asset" char(50),
  "pabrikan" char(50),
  "negara" char(10),
  "tahun_produksi" int4,
  "penyedia" char(50),
  "tahun_perolehan" int4,
  "kondisi" char(50),
  "harga" int4,
  "umur_ekonomis" int4,
  "no_seri_pabrik" char(20),
  "berat" float4,
  "dimensi" float4,
  "diameter" float4,
  "jenis_amunisi" char(50),
  "kecepatan_luncur" float4,
  "penetrasi" float4
);

